### ISSUE TITLE
No Data Pulled on DSM 6.1

### ISSUE THREAD

**Issue by danilpremgi** [jperillo/Synology_dashboard_grafana#4]
The dashboard is not showing any data when I run the telegraf -test I get the error but I don't believe these related to the dashboard:
_
Cannot find module (IF-MIB): At line 1 in (none)
IF-MIB::ifTable: Unknown Object Identifier_

Running it on Ubuntu 16.04, any suggestions what I'm doing wrong?

**Comment by danilpremgi** [comment]
SNMP MIBs not downloaded https://github.com/WaterByWind/grafana-dashboards/issues/3

Issued resolved.

**Comment by daodevinc** [comment]
Hi have the same error. But i use Telegraf at Docker container, and when i reboot container, mibs-downloader is deleted. Have you a script to install mibs file at the docker file ?
