### ISSUE TITLE
Traffic Stopped Displaying

### ISSUE THREAD

**Issue by pltaylor** [jperillo/Synology_dashboard_grafana#7]
I have set up telegraf with snmp, downloaded the Mib files, edited my telegraf.conf file, and setup influx and grafana and everything appeared to work for a day or 2 and then the Traffic data stopped showing up.  The history also is not there any more.  I don't believe I changed anything relevant, but obviously something has changed.  Do you have any suggestions for ways to troubleshoot this?  I'm out of ideas.
![image](https://user-images.githubusercontent.com/986333/62771386-16e6c400-ba6b-11e9-832b-285425aeb11a.png)

**Comment by i03oo3** [comment]
I have the same issue. Was this ever resolved?

**Comment by pltaylor** [comment]
@i03oo3 I'm going to mark this as resolved as I eventually went back and redid my telegraf.conf file and got everything to work.  Not sure what I did wrong the first time, but redoing it fixed it.
